/**
 * AI Proposal JSON Parser & Sanitizer
 * Validates and standardizes proposal sections generated by AI into structured format.
 */

export const parseAiProposalJson = (rawInput) => {
  if (!rawInput) {
    return { success: false, error: "Input is empty." };
  }

  let text = typeof rawInput === "string" ? rawInput.trim() : JSON.stringify(rawInput);

  // Strip markdown code fences if present (```json ... ``` or ``` ...)
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (fenceMatch) {
    text = fenceMatch[1].trim();
  } else {
    const firstBrace = text.indexOf("{");
    const lastBrace = text.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      text = text.substring(firstBrace, lastBrace + 1).trim();
    }
  }

  try {
    const parsed = typeof rawInput === "object" && rawInput !== null ? rawInput : JSON.parse(text);

    if (!parsed || typeof parsed !== "object") {
      return { success: false, error: "Parsed content is not a valid JSON object." };
    }

    if (!parsed.sections || !Array.isArray(parsed.sections) || parsed.sections.length === 0) {
      return { success: false, error: "JSON is missing the 'sections' array." };
    }

    // Ensure tables array exists
    if (!parsed.tables || !Array.isArray(parsed.tables)) {
      parsed.tables = [];
    }

    // Post-process sections: Clean HTML, ensure paragraph tags and list tags
    parsed.sections = parsed.sections.map((sec) => {
      let content = sec.content || "";

      // If content has bullet symbols like • or -, convert to <ul><li>
      if (content.includes("•")) {
        let plainText = content.replace(/<[^>]+>/g, "");
        const parts = plainText.split("•");

        let intro = parts[0].trim();
        let items = parts.slice(1).map((s) => s.trim()).filter(Boolean);

        let htmlContent = "";
        if (intro) {
          htmlContent += `<p>${intro}</p>`;
        }
        if (items.length > 0) {
          htmlContent += "<ul>";
          items.forEach((item) => {
            htmlContent += `<li>${item}</li>`;
          });
          htmlContent += "</ul>";
        }
        content = htmlContent;
      } else if (content && !content.includes("<p>") && !content.includes("<ul>") && !content.includes("<ol>")) {
        content = `<p>${content}</p>`;
      }

      return {
        type: sec.type || "title",
        title: sec.title || "",
        content: content,
      };
    });

    return {
      success: true,
      data: {
        sections: parsed.sections,
        tables: parsed.tables,
      },
    };
  } catch (err) {
    return {
      success: false,
      error: `Could not parse proposal JSON: ${err.message}`,
    };
  }
};
