/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by scripts/generate-base64-images.js during build.
 * 
 * Contains remote asset URLs pointing to the Express backend.
 * This resolves react-pdf/renderer v4 image loading and rendering issues.
 */

const baseURL = process.env.NEXT_PUBLIC_APP_BASE_URL || "http://localhost:5000";
const cleanBaseURL = baseURL.endsWith("/") ? baseURL.slice(0, -1) : baseURL;

export const COVER_BG = `${cleanBaseURL}/newBg.png`;
export const LOGO = `${cleanBaseURL}/download.jpg`;
export const HEADER_IMG = `${cleanBaseURL}/new-header.png`;
export const FOOTER_IMG = `${cleanBaseURL}/footer.png`;
export const CONTACT_PAGE = `${cleanBaseURL}/proposal-contact.png`;
export const HT_LOGO = `${cleanBaseURL}/ht-logo.png`;
