/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by scripts/generate-base64-images.js during build.
 * 
 * Contains relative asset paths for all static design assets.
 * These are resolved to Base64 at PDF export time.
 */

export const COVER_BG = "/newBg.png";
export const LOGO = "/ht-logo.png";
export const HEADER_IMG = "/header.png";
export const FOOTER_IMG = "/footer.png";
export const CONTACT_PAGE = "/proposal-contact.png";
export const HT_LOGO = "/ht-logo.png";
export const ARTBOARD_1 = "/Artboard1.jpg";
export const ARTBOARD_2 = "/Artboard 2.jpg";
export const ARTBOARD_3 = "/Artboard 3.jpg";
export const ARTBOARD_4 = "/Artboard 4.jpg";
export const ARTBOARD_5 = "/Artboard 5.jpg";
